#!/usr/bin/env python3
"""
Inverted Pendulum with a single URDF 'cart_pendulum_wheels.urdf':
  - Link0: chassis
  - Link1..4: 4 wheels, revolve about x-axis
  - Link5: rod, revolve about y from chassis top
  - Link6: bob, fixed at rod top

We set initial angles=0 so it starts upright and still.
We apply an LQR control by applying a horizontal force on the chassis link 
to keep x=0, rod angle=0. 
No sliding at start if friction is high and no net force is generated by LQR 
( error=0 => force=0 ). 
You can left-click to poke, or at t=2 we do a small disturbance. 
Runs until you press 'q' or close window.
"""

import pybullet as pb
import pybullet_data
import math, time, random
import numpy as np
import matplotlib.pyplot as plt

# If not defined:
MOUSE_BUTTON_LEFT = 0
KEY_WAS_TRIGGERED = 1

###############################################################################
# 1) Parameter Class
###############################################################################
class Params:
    def __init__(self):
        # LQR Gains => F = -K [ x - x_des, xdot, theta, thetadot ]
        self.x_des = 0.0
        self.K_lqr = np.array([-20.0, -5.0, 40.0, 7.5])

        # sensor noise
        self.use_noise = True
        self.noise_std_x     = 0.002
        self.noise_std_xdot  = 0.002
        self.noise_std_th    = 0.002
        self.noise_std_thdot = 0.002
        self.alpha_filter    = 0.9

        # control saturation
        self.use_saturation = True
        self.max_force = 50.0

        # disturbance at t=2
        self.disturb_time  = 2.0
        self.disturb_force = 5.0
        self.tip_angle_deg = 5.0

        # simulation
        self.dt = 1.0/240.0
        self.gravity = 9.81

###############################################################################
# 2) Sensor
###############################################################################
class Sensor:
    def __init__(self, p:Params):
        self.p = p
        self.prev_meas = None

    def measure_and_filter(self, x, xdot, theta, thetadot):
        if self.p.use_noise:
            xn     = x     + random.gauss(0, self.p.noise_std_x)
            xdn    = xdot  + random.gauss(0, self.p.noise_std_xdot)
            thn    = theta + random.gauss(0, self.p.noise_std_th)
            thdn   = thetadot + random.gauss(0, self.p.noise_std_thdot)
        else:
            xn, xdn, thn, thdn = x, xdot, theta, thetadot

        meas = np.array([xn, xdn, thn, thdn])
        if self.prev_meas is None:
            self.prev_meas = meas
            return meas

        alpha= self.p.alpha_filter
        filtered= alpha*self.prev_meas + (1.0-alpha)*meas
        self.prev_meas= filtered
        return filtered

###############################################################################
# 3) LQR Controller
###############################################################################
class Controller:
    def __init__(self, p:Params):
        self.p = p

    def compute_force(self, meas):
        x, xdot, theta, thetadot = meas
        error= np.array([ (x - self.p.x_des), xdot, theta, thetadot ])
        F= - self.p.K_lqr.dot(error)
        if self.p.use_saturation:
            F= np.clip(F, -self.p.max_force, self.p.max_force)
        return F

###############################################################################
# 4) The Simulation
###############################################################################
class InvertedPendulumSim:
    def __init__(self, p:Params):
        self.p= p
        self.sensor= Sensor(p)
        self.ctrl= Controller(p)

        self.cid= None
        self.body_id= None
        self.n_joints= 0

        self.t_data= []
        self.x_data= []
        self.th_data= []
        self.f_data= []

        self.start_time= None
        self.last_time= None

    def setup_sim(self):
        # connect
        self.cid= pb.connect(pb.GUI)
        pb.setAdditionalSearchPath(pybullet_data.getDataPath())
        pb.setGravity(0,0, -self.p.gravity)
        pb.setRealTimeSimulation(0)

        # load plane
        plane_id= pb.loadURDF("plane.urdf", useFixedBase=True)
        # friction so wheels won't slip
        pb.changeDynamics(plane_id, -1, lateralFriction=10.0, spinningFriction=1.0, rollingFriction=0.02)

        # load single URDF
        self.body_id= pb.loadURDF("cart_pendulum_wheels.urdf",
                                  basePosition=[0,0,0],
                                  useFixedBase=False)
        self.n_joints= pb.getNumJoints(self.body_id)

        # set friction on main body
        pb.changeDynamics(self.body_id, -1, lateralFriction=10.0, spinningFriction=1.0, rollingFriction=0.02)

        # disable motors so the wheels and pendulum revolve freely
        for j in range(self.n_joints):
            jinfo= pb.getJointInfo(self.body_id, j)
            jname= jinfo[1].decode("utf-8")
            # set VELOCITY_CONTROL with force=0 => free
            pb.setJointMotorControl2(self.body_id, j,
                                     controlMode=pb.VELOCITY_CONTROL,
                                     targetVelocity=0,
                                     force=0)

        # we want initial angles=0 => rod upright, wheels=0
        # reset them all
        for j in range(self.n_joints):
            pb.resetJointState(self.body_id, j, targetValue=0, targetVelocity=0)

        # step a few times to let it settle
        for _ in range(50):
            pb.stepSimulation()

    def handle_mouse(self):
        events= pb.getMouseEvents()
        if not events:
            return
        cam= pb.getDebugVisualizerCamera()
        if len(cam)<11:
            return
        w= cam[0]; h= cam[1]
        view= cam[2]; proj= cam[3]
        for e in events:
            etype= e[0]
            state= e[1]
            mx= e[2]
            my= e[3]
            if (etype==MOUSE_BUTTON_LEFT) and (state & KEY_WAS_TRIGGERED):
                rayFrom, rayTo= self.compute_ray(mx,my,w,h,view,proj)
                hits= pb.rayTest(rayFrom,rayTo)
                if hits and hits[0][0]>=0:
                    bUid= hits[0][0]
                    hitFrac= hits[0][2]
                    hitPos= [rayFrom[i]+(rayTo[i]-rayFrom[i])*hitFrac for i in range(3)]
                    fMag=5.0
                    fDir= [rayTo[i]-rayFrom[i] for i in range(3)]
                    dist= math.sqrt(sum(ff*ff for ff in fDir))
                    if dist>1e-9:
                        invd=1./dist
                        fDir=[a*invd for a in fDir]
                        fVec=[fMag*a for a in fDir]
                        pb.applyExternalForce(bUid, -1, fVec, hitPos, pb.WORLD_FRAME)

    def compute_ray(self,mx,my,w,h,view,proj):
        ndcX= (mx-w/2.)/(w/2.)
        ndcY= (h/2.-my)/(h/2.)
        import numpy as np
        invV= np.linalg.inv(np.array(view).reshape((4,4)).T)
        invP= np.linalg.inv(np.array(proj).reshape((4,4)).T)
        nearPt= np.array([ndcX, ndcY, -1,1])
        farPt = np.array([ndcX, ndcY,  1,1])
        nearCam= invP.dot(nearPt); nearCam/= nearCam[3]
        farCam= invP.dot(farPt);   farCam /= farCam[3]
        nearWorld= invV.dot(nearCam); nearWorld/= nearWorld[3]
        farWorld = invV.dot(farCam);  farWorld/= farWorld[3]
        rayFrom= nearWorld[:3]
        rayTo=   farWorld[:3]
        return rayFrom, rayTo

    def get_state(self):
        """
        We want cart x, xdot, rod angle, rod angular vel.
        The 'rod' revolve joint is named 'joint_pendulum' 
        or the 5th link's joint in the URDF.
        """
        # chassis base
        basePos, baseOri= pb.getBasePositionAndOrientation(self.body_id)
        baseVel, baseAng= pb.getBaseVelocity(self.body_id)
        x= basePos[0]
        xdot= baseVel[0]

        # find pendulum joint
        pend_index= None
        for j in range(self.n_joints):
            jinfo= pb.getJointInfo(self.body_id,j)
            jname= jinfo[1].decode("utf-8")
            if "pendulum" in jname:
                pend_index= j
                break
        if pend_index is None:
            # fallback: might be joint5
            pend_index= self.n_joints-2  # or something

        jState= pb.getJointState(self.body_id, pend_index)
        theta= jState[0]
        thetadot= jState[1]
        return x, xdot, theta, thetadot

    def run(self):
        self.setup_sim()
        self.start_time= time.time()
        self.last_time= self.start_time

        while True:
            # check for 'q'
            keys= pb.getKeyboardEvents()
            if ord('q') in keys and (keys[ord('q')] & KEY_WAS_TRIGGERED):
                break
            if not pb.getConnectionInfo().get('isConnected', True):
                break

            now= time.time()
            dt= now- self.last_time
            if dt< self.p.dt:
                time.sleep(self.p.dt- dt)
                now= time.time()
            self.last_time= now
            t_run= now- self.start_time

            x, xdot, theta, thetadot= self.get_state()
            meas= self.sensor.measure_and_filter(x, xdot, theta, thetadot)
            F_ctrl= self.ctrl.compute_force(meas)

            F_extra=0.0
            if abs(t_run- self.p.disturb_time)< 0.5*self.p.dt:
                F_extra+= self.p.disturb_force
                # forcibly tip the rod joint
                pend_index= None
                for j in range(self.n_joints):
                    jinfo= pb.getJointInfo(self.body_id,j)
                    jname= jinfo[1].decode("utf-8")
                    if "pendulum" in jname:
                        pend_index= j
                        break
                if pend_index is not None:
                    old_th= pb.getJointState(self.body_id, pend_index)[0]
                    new_th= old_th + math.radians(self.p.tip_angle_deg)
                    pb.resetJointState(self.body_id, pend_index, new_th, 0)

            F_total= F_ctrl + F_extra
            # apply horizontal force to the chassis base
            pb.applyExternalForce(self.body_id, -1,
                                  forceObj=[F_total,0,0],
                                  posObj=[0,0,0],
                                  flags= pb.WORLD_FRAME)

            self.handle_mouse()
            pb.stepSimulation()

            self.t_data.append(t_run)
            self.x_data.append(x)
            self.th_data.append(theta)
            self.f_data.append(F_total)

        return np.array(self.t_data), np.array(self.x_data), np.array(self.th_data), np.array(self.f_data)

    def plot_results(self, t_log, x_log, th_log, f_log):
        fig, axs= plt.subplots(3,1, figsize=(8,6))
        axs[0].plot(t_log, x_log, 'b-', label='Cart X(m)')
        axs[0].grid(True)
        axs[0].legend()

        axs[1].plot(t_log, np.degrees(th_log), 'r-', label='Pendulum Angle (deg)')
        axs[1].grid(True)
        axs[1].legend()

        axs[2].plot(t_log, f_log, 'm-', label='Control Force (N)')
        axs[2].grid(True)
        axs[2].legend()

        plt.suptitle("Single URDF w/ real wheels, rod revolve, bob fixed, LQR => Press 'q' to quit")
        plt.tight_layout()
        plt.show()

def main():
    print("Single URDF with wheels, rod, bob. Starting upright & still. Press 'q' to quit.")
    p= Params()
    sim= InvertedPendulumSim(p)
    t_log, x_log, th_log, f_log= sim.run()
    print("Exiting. Plotting logs.")
    sim.plot_results(t_log, x_log, th_log, f_log)

if __name__=="__main__":
    main()
